PASS = """Beliver123@"""
k = ["naaz arvee music", "all night archit"]

acpw = {

"teramera@yahoo.com":PASS,
"RobertrPfz132452@yahoo.com":PASS,
#     "RuthZrt948379@yahoo.com":PASS,
# "WalterQFR246211@yahoo.com":PASS,
#     "NormaCrMt420535@yahoo.com":PASS,
# "BrittanyUEZT31969@yahoo.com":PASS,
# "MichaelBtxa823131@yahoo.com":PASS,
# "AaronyrU199592@yahoo.com":PASS,
#     "LanniePjyV390130@yahoo.com":PASS,
# "DanielNNWV457461@yahoo.com":PASS,
# "DarrickevH70956@yahoo.com":PASS,
# "FredQFR257430@yahoo.com":PASS,
# "JoanXCL582334@yahoo.com":PASS,
# "CherylKCwk648509@yahoo.com":PASS,
# "NathanialTGd123496@yahoo.com":PASS,
# "MarthaZDLK916973@yahoo.com":PASS,
# "JessieXwA556918@yahoo.com":PASS,
# "GuillermorPfz655592@yahoo.com":PASS,
# "ElwoodXCL200458@yahoo.com":PASS,
# # "AlexanderSe993032@yahoo.com":PASS,
# "YolandavhL964095@yahoo.com":PASS,
# "MattiePjyV560140@yahoo.com":PASS,
# "RobertJMm790027@yahoo.com":PASS,
# "Janetpoop7975@yahoo.com":PASS,
# "Alexanderpoop8921@yahoo.com":PASS,
# "Johnpoop8751@yahoo.com":PASS,
# "JosephfLa597805@yahoo.com":PASS,
}


bcacpw = {}
playlists = ["https://open.spotify.com/playlist/0dz8XJ8HSKns8A7730XVZh"]
print("no of accounts", len(acpw))
strlist = ["qrLT",
           "TyNu",
           "Btxa",
           "CrMt",
           "ZDLK",
           "TfTN",
           "HZSd",
           "dvAj",
           "gyMX",
           "MKAr",
           "YpYz",
           "xRPh",
           "wzbu",
           "tGzu",
           "HqWz",
           "RMcd",
           "KZgD",
           "rPfz",
           "dkzN",
           "PjyV",
           "PVtq",
           "TgVa",
           "UEZT",
           "LQLf",
           "PNqR",
           "NNWV",
           "qGPk",
           "Jdpu",
           "KCwk",
           "mLBe",
           "YBvL",
           "jbTv",
           "zSid",
           "MBMR",
           "AVpq",
           "TYU",
           "pNN",
           "mZx",
           "cfw",
           "vhL",
           "CBe",
           "gwD",
           "Zrt",
           "YBj",
           "QFR",
           "CNy",
           "WdK",
           "kAR",
           "vnb",
           "cEw",
           "JQU",
           "wjR",
           "paw",
           "qEj",
           "rUL",
           "aGT",
           "Sxe",
           "Da",
           "XCL",
           "iCU",
           "GZX",
           "YiS",
           "MyV",
           "Nrf",
           "Se",
           "Wpn",
           "evH",
           "tnM",
           "ivf",
           "fZR",
           "yrU",
           "tdS",
           "UJm",
           "fLa",
           "vTm",
           "mmk",
           "uMe",
           "XwA",
           "DuQ",
           "VTj",
           "RBB",
           "JMm",
           "EtA",
           "trTGd",
           "uPA",
           "opo",
           "ooo",
           "kak",
           "ljk",
           "kjk",
           ]

